### ISSUE TITLE
NTR?

### ISSUE THREAD

**Issue by 100pcrack** [RedInquisitive/Screenshot-Tool#1]
How about an NTR screenshot merge funcion?

**Comment by RedInquisitive** [comment]
Hmmm, I'm not quite sure the format of those. If you share some general information (name scheme, dimensions etc) I could definitely do that!

**Comment by 100pcrack** [comment]
The screenshots are stored on the root of the SD card with the name of "bot_0000.bmp" or "top_0001.bmp"
Note: As github doesn't allow to upload bmp files, I will convert them to png for upload.
Example bot_0000.bmp file:
![bot_0000.bmp](http://i.imgur.com/hx843hw.png)
Example top_0001.bmp file:
![top_0001.bmp](http://i.imgur.com/yLsanhA.png)
Thanks for your effort!

**Comment by RedInquisitive** [comment]
I'll work on it soon, just give me a second. I'll probably just have it look through the same folder for both ninjahax and NTR, so you should be able to run both at the same time if both types are in the same folder.

**Comment by 100pcrack** [comment]
I don't think so, but I had the 3D mode enabled when I took the screenshots.
Thanks!

**Comment by RedInquisitive** [comment]
Alright. ATM it'll export all of them as PNGs, is that OK, or should I leave NTR screenshots as bmps?

(Oh, and what is NTR? Can it screenshot anywhere? it is a CFW, right? I might use it if it can screenshot MH4U with it (hans can't launch MH4U :cry: ) I'm on rxtools 10.3.0-28U so I might switch to it if I have some more info)

**Comment by RedInquisitive** [comment]
Alright, done! Try it out. (I don't know if I should bump the GBATemp thread too, it's probably too old. I'm kinda' bad with forums anyway :laughing: )

**Comment by 100pcrack** [comment]
NTR CFW. Google it. It's a cia that runs in emunand and allows you to take screenshots in ANY game and to use cheats.

**Comment by 100pcrack** [comment]
Ok, it works very good!
Thanks for your work!!!
NTR proof:
![ntr_1_merged](https://cloud.githubusercontent.com/assets/15199763/12455820/6def9b18-bf9d-11e5-810f-57b89f647a6d.png)
