### ISSUE TITLE
NTR-ES?

### ISSUE THREAD

**Issue by 100pcrack** [RedInquisitive/Screenshot-Tool#3]
Could you implement NTR Spanish support?
The same structure as NTR screenshot but:

- **sup_0000.bmp** instead of **top_0000.bmp**

- **inf_0000.bmp** instead of **bot_0000.bmp**
Thanks for your awestome work!

**Comment by RedInquisitive** [comment]
Sure! IDK if it will be done right now because I have some real life tasks to get out of the way first.

I don't think this should be too hard, so I think you should be able to expect it today (within 8 hours). Just bump this if I forget haha.

**Comment by 100pcrack** [comment]
Thanks!

**Comment by RedInquisitive** [comment]
Sorry it took me so long! I'll go ahead and compile some binaries for the latest java run time. Hope it works!
