### ISSUE TITLE
TestMenu

### ISSUE THREAD

**Issue by Delphox** [RedInquisitive/Screenshot-Tool#4]
Could you add support for [TestMenu](https://www.3dbrew.org/wiki/3DS_Development_Unit_GUI#Test_Menu) screenshots? Although it's a pretty obscure way to screenshot it's the only way that's possible to take screenshots on extended RAM games on Old 3DS (which have been growing in popularity lately).

The wiki shows the naming format, and here's a recent screenshot folder of mine for reference as well.
![image](https://cloud.githubusercontent.com/assets/5883538/20898041/eeffa4b8-bb0b-11e6-9905-abc4e946c5de.png)

**Comment by RedTopper** [comment]
Yeah, I'll totally do that. I had no idea about TestMenu, seems really interesting. I'll see if I can get it done soon. 

Is there a way to enable TestMenu on  a non-dev device? I use CFW+Luma, and I really want to take screenshots in extended RAM mode haha!

**Comment by Delphox** [comment]
Yep, check this http://pastebin.com/FfzTJXzW

And thanks man!

**Comment by RedTopper** [comment]
Alright, go ahead and try the latest release. Let me know how it goes!

(I'll let you close this issue if it works)

Sidenote: If you want, you can add all of your NTR/TestMenu/ninjahax screenshots into one folder and it will match them  all, no  need to run the program 3 times!

**Comment by Delphox** [comment]
Just tested and worked perfectly, thank you so much! Thanks for the tip too!

(I deleted my previous comment just in case, since it might not be a good idea to have it linked here since the pastebin contains not-so-cool CIAs, but you already got it so all good)
