### ISSUE TITLE
Suggestion: Add current luma3ds filename format

### ISSUE THREAD

**Issue by mariomadproductions** [RedInquisitive/Screenshot-Tool#5]
example:
2018-10-12_21-17-00.723_top.bmp
2018-10-12_21-17-00.723_bot.bmp

**Comment by RedTopper** [comment]
I had no idea anyone still used this project but I could do that!

**Comment by RedTopper** [comment]
Can you check to see if the new binary in the repository root works for you? if it does I'll go ahead and make a release and close the issue.

**Comment by mariomadproductions** [comment]
It works. Thanks.
